name: production

on:
  push:
    branches:
      - main

jobs:
  e2e:
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Run Cypress 🌲
        uses: cypress-io/github-action@v4
        with:
        env:
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
